# @generated by datamodel-codegen:
#   filename:  extent/midi_interval.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type DurationItem = Annotated[float, Meta(ge=0.0)]


class MidiInterval(Struct, tag_field="extent_type", tag="midi_interval"):
    tick: Annotated[
        list[float], Meta(description="Array of interval start times in MIDI ticks.")
    ]
    duration: Annotated[
        list[DurationItem],
        Meta(description="Array of interval durations in MIDI ticks."),
    ]
