# @generated by datamodel-codegen:
#   filename:  extent/pixel_box.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type WidthItem = Annotated[float, Meta(ge=0.0)]


type HeightItem = Annotated[float, Meta(ge=0.0)]


class PixelBoxExtent(Struct, tag_field="extent_type", tag="pixel_box"):
    x: Annotated[list[float], Meta(description="Array of x-coordinates in pixels.")]
    width: Annotated[
        list[WidthItem], Meta(description="Array of box widths in pixels.")
    ]
    y: Annotated[list[float], Meta(description="Array of y-coordinates in pixels.")]
    height: Annotated[
        list[HeightItem], Meta(description="Array of box heights in pixels.")
    ]
