# @generated by datamodel-codegen:
#   filename:  extent/score_interval.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

from .. import core


class ScoreInterval(Struct, tag_field="extent_type", tag="score_interval"):
    quarter: Annotated[
        list[core.Fraction],
        Meta(description="Array of interval start times in fractional quarter notes."),
    ]
    duration: Annotated[
        list[core.FractionNonnegative],
        Meta(description="Array of interval durations in fractional quarter notes."),
    ]
