# @generated by datamodel-codegen:
#   filename:  extent/score_quarter.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

from .. import core


class ScoreQuarterNotes(Struct, tag_field="extent_type", tag="score_quarter"):
    quarter: Annotated[
        list[core.Fraction], Meta(description="An array of fractional quarter values.")
    ]
