# @generated by datamodel-codegen:
#   filename:  extent/times.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class Timestamps(Struct, tag_field="extent_type", tag="timestamps"):
    time: Annotated[
        Annotated[Array, "float32"], Meta(description="An N array of time values.")
    ]
