# @generated by datamodel-codegen:
#   filename:  extent/times.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class Times(Struct, tag_field="extent_type", tag="time"):
    time: Annotated[list[float], Meta(description="An array of time values.")]
