# @generated by datamodel-codegen:
#   filename:  extent/times.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type TimeItem = Annotated[float, Meta(ge=0.0)]


class Timestamps(Struct, tag_field="extent_type", tag="time"):
    time: Annotated[list[TimeItem], Meta(description="An N array of time values.")]
