# @generated by datamodel-codegen:
#   filename:  extent/time_interval.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class TimeIntervalExtent(Struct, tag_field="extent_type", tag="time_interval"):
    times: Annotated[
        Array,
        Meta(description="Array of start time timestamps in seconds."),
    ]
    durations: Annotated[
        Array,
        Meta(description="Array of interval durations in seconds."),
    ]
