# @generated by datamodel-codegen:
#   filename:  extent/time_frequency_box.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class TimeFrequencyBoxExtent(Struct, tag_field="extent_type", tag="TimeFrequencyBox"):
    time: Annotated[
        Annotated[Array, "float32"],
        Meta(description="Array of start time timestamps in seconds."),
    ]
    duration: Annotated[
        Annotated[Array, "float32"],
        Meta(description="Array of box durations in seconds."),
    ]
    freq_min: Annotated[
        Annotated[Array, "float32"],
        Meta(description="Array of minimum frequencies in Hz."),
    ]
    freq_max: Annotated[
        Annotated[Array, "float32"],
        Meta(description="Array of maximum frequencies in Hz."),
    ]
