# @generated by datamodel-codegen:
#   filename:  payload/beat.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class BeatPositionPayload(Struct, tag_field="payload_type", tag="beat"):
    values: Annotated[
        Array,
        Meta(
            description="The metric position of the beat within the measure (e.g., 1 for downbeat, 2, 3, 4)."
        ),
    ]
