# @generated by datamodel-codegen:
#   filename:  payload/chord.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class ChordPayload(Struct, tag_field="payload_type", tag="chord"):
    values: Annotated[
        Array, Meta(description="A musical chord string in extended Harte notation.")
    ]
