# @generated by datamodel-codegen:
#   filename:  payload/ext.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import Meta, Struct


class ExtensionPayload(Struct, tag_field="payload_type", tag="ext"):
    ext_schema: Annotated[
        str,
        Meta(
            description="Identifier for the schema defining the items in the value array."
        ),
    ]
    value: Annotated[
        list[Any],
        Meta(description="Annotations consisting of structured extension data."),
    ]
