# @generated by datamodel-codegen:
#   filename:  payload/key_mode.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class KeyModePayload(Struct, tag_field="payload_type", tag="key_mode"):
    values: Annotated[
        Array, Meta(description="Key and optional mode (major/minor or Greek modes)")
    ]
