# @generated by datamodel-codegen:
#   filename:  payload/key_mode.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type Value = Annotated[
    str,
    Meta(
        pattern="^N|([A-G][b#]?)(:(major|minor|ionian|dorian|phrygian|lydian|mixolydian|aeolian|locrian))?$"
    ),
]


class KeyModePayload(Struct, tag_field="payload_type", tag="key_mode"):
    values: Annotated[
        list[Value],
        Meta(description="Key and optional mode (major/minor or Greek modes)"),
    ]
