# @generated by datamodel-codegen:
#   filename:  payload/lyrics.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class LyricsPayload(Struct, tag_field="payload_type", tag="lyrics"):
    value: Annotated[list[str], Meta(description="Open strings for lyrics annotations")]
