# @generated by datamodel-codegen:
#   filename:  payload/lyrics.json

from __future__ import annotations

from typing import Annotated, Literal

from msgspec import Meta, Struct


class LyricsPayload(Struct):
    payload_type: Literal["lyrics"]
    values: Annotated[
        list[str], Meta(description="Open strings for lyrics annotations")
    ]
