# @generated by datamodel-codegen:
#   filename:  payload/mood_thayer.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class MoodThayerPayload(Struct, tag_field="payload_type", tag="mood_thayer"):
    valence: Annotated[list[float], Meta(description="Valence")]
    arousal: Annotated[list[float], Meta(description="Arousal")]
