# @generated by datamodel-codegen:
#   filename:  payload/mood_thayer.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type Value = Annotated[list[float], Meta(max_length=2, min_length=2)]


class MoodThayerPayload(Struct, tag_field="payload_type", tag="mood_thayer"):
    values: Annotated[
        list[Value], Meta(description="Thayer mood model: (valence, arousal)")
    ]
