# @generated by datamodel-codegen:
#   filename:  payload/mood_thayer.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class MoodThayerPayload(Struct, tag_field="payload_type", tag="mood_thayer"):
    values: Annotated[Array, Meta(description="Thayer mood model: (valence, arousal)")]
