# @generated by datamodel-codegen:
#   filename:  payload/note_hz.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class NoteHzPayload(Struct, tag_field="payload_type", tag="note_hz"):
    values: Annotated[Array, Meta(description="Note pitches in Hz")]
