# @generated by datamodel-codegen:
#   filename:  payload/note_hz.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type Value = Annotated[float, Meta(ge=0.0)]


class NoteHzPayload(Struct, tag_field="payload_type", tag="note_hz"):
    values: Annotated[list[Value], Meta(description="Note pitches in Hz")]
