# @generated by datamodel-codegen:
#   filename:  payload/object.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import Meta, Struct


class ObjectPayload(Struct, tag_field="payload_type", tag="object"):
    value: Annotated[
        list[dict[str, Any]],
        Meta(description="Annotations consisting of structured object data"),
    ]
