# @generated by datamodel-codegen:
#   filename:  payload/onset.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import Meta, Struct


class OnsetPayload(Struct, tag_field="payload_type", tag="onset"):
    values: Annotated[list[Any], Meta(description="Onset event markers")]
