# @generated by datamodel-codegen:
#   filename:  payload/onset.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class OnsetPayload(Struct, tag_field="payload_type", tag="onset"):
    values: Annotated[Array, Meta(description="Onset event markers")]
