# @generated by datamodel-codegen:
#   filename:  payload/pattern_jku.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class PatternJkuPayload(Struct, tag_field="payload_type", tag="pattern_jku"):
    values: Annotated[
        Array,
        Meta(
            description="Pattern (MIDI pitch), including staff height, voice number, occurrence id, and pattern id"
        ),
    ]
