# @generated by datamodel-codegen:
#   filename:  payload/pattern_jku.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class Value(Struct):
    midi_pitch: float
    morph_pitch: float
    staff: float
    pattern_id: Annotated[float, Meta(ge=1.0)]
    occurrence_id: Annotated[float, Meta(ge=1.0)]


class PatternJkuPayload(Struct, tag_field="payload_type", tag="pattern_jku"):
    values: Annotated[
        list[Value],
        Meta(
            description="Pattern (MIDI pitch), including staff height, voice number, occurrence id, and pattern id"
        ),
    ]
