# @generated by datamodel-codegen:
#   filename:  payload/pitch_class.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class PitchClassPayload(Struct, tag_field="payload_type", tag="pitch_class"):
    values: Annotated[
        Array, Meta(description="Pitch class in (tonic, pitch class) format")
    ]
