# @generated by datamodel-codegen:
#   filename:  payload/pitch_contour_hz.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class PitchContourPayload(Struct, tag_field="payload_type", tag="pitch_contour"):
    index: Annotated[
        Array, Meta(description="Pitch contour indices/IDs.")
    ]
    frequency: Annotated[
        Array, Meta(description="Pitch contour frequency values in Hz.")
    ]
    voicing: Annotated[
        Array, Meta(description="Pitch contour voicing values/booleans.")
    ]
