# @generated by datamodel-codegen:
#   filename:  payload/pitch_contour_hz.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import Meta, Struct


class PitchContourPayload(Struct, tag_field="payload_type", tag="pitch_contour"):
    values: Annotated[
        list[dict[str, Any]],
        Meta(description="Pitch contours: (index, frequency, voicing)"),
    ]
