# @generated by datamodel-codegen:
#   filename:  payload/relation.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType


class RelationEnum(StrEnum):
    cover = "cover"
    quote = "quote"
    medley_part = "medley_part"
    sample = "sample"
    interpolation = "interpolation"
    remix = "remix"
    live_performance = "live_performance"


class RelationPayload(Struct, tag_field="payload_type", tag="relation"):
    """
    Columnar payload defining relationships between works (covers, quotes, etc).
    """

    performance_id: str
    value: Annotated[
        list[str], Meta(description="Array of referenced work or clique identifiers.")
    ]
    relation: (
        Annotated[
            list[RelationEnum],
            Meta(description="Array of relation types parallel to work_id."),
        ]
        | UnsetType
    ) = UNSET
