# @generated by datamodel-codegen:
#   filename:  payload/segment_multi.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class Value(Struct):
    label: str
    level: Annotated[int, Meta(ge=0)]


class MultiSegmentPayload(Struct, tag_field="payload_type", tag="multi_segment"):
    values: Annotated[
        list[Value], Meta(description="Multi-level segmentation: (label, level)")
    ]
