# @generated by datamodel-codegen:
#   filename:  payload/segment_multi.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class MultiSegmentPayload(Struct, tag_field="payload_type", tag="multi_segment"):
    label: Annotated[Array, Meta(description="Multi-level segmentation labels.")]
    level: Annotated[Array, Meta(description="Multi-level segmentation levels.")]
