# @generated by datamodel-codegen:
#   filename:  payload/tag_open.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class TagOpenPayload(Struct, tag_field="payload_type", tag="tag_open"):
    value: Annotated[
        list[str], Meta(description="Open tag vocabularies allow all strings")
    ]
