# @generated by datamodel-codegen:
#   filename:  payload/tempo.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type ValueItem = Annotated[float, Meta(ge=0.0)]


class TempoPayload(Struct, tag_field="payload_type", tag="tempo"):
    value: Annotated[
        list[ValueItem],
        Meta(description="Tempo measurements, in beats per minute (BPM)"),
    ]
