# @generated by datamodel-codegen:
#   filename:  payload/tempo.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class TempoPayload(Struct, tag_field="payload_type", tag="tempo"):
    values: Annotated[
        Array, Meta(description="Tempo measurements, in beats per minute (BPM)")
    ]
