# @generated by datamodel-codegen:
#   filename:  annotation.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import UNSET, Meta, UnsetType

from ...base import BoppBase
from . import confidences, extents, payloads
from . import metadata as metadata_1


class Annotation(BoppBase):
    media_id: Annotated[str, Meta(pattern="^[a-zA-Z0-9]+:.*$")]
    bopp_version: Annotated[
        str,
        Meta(
            description="The Semantic Version of the BOPP schema (e.g., 1.0)",
            pattern="^1\\.\\d+$",
        ),
    ]
    payload: Annotated[
        payloads.AnyPayload,
        Meta(description="The parallel array of values (e.g., beat, chord)"),
    ]
    metadata: (
        Annotated[
            metadata_1.AnnotationMetadata,
            Meta(description="The metadata describing the annotation"),
        ]
        | UnsetType
    ) = UNSET
    extent: (
        Annotated[
            extents.AnyExtent,
            Meta(
                description="The parallel array of time/space boundaries (e.g., time_interval, point)"
            ),
        ]
        | UnsetType
    ) = UNSET
    confidence: (
        Annotated[
            confidences.AnyConfidence,
            Meta(description="Optional parallel array of likelihoods or votes"),
        ]
        | UnsetType
    ) = UNSET
    sandbox: (
        Annotated[
            Any,
            Meta(
                description="Unstructured storage area for arbitrary user-defined data"
            ),
        ]
        | UnsetType
    ) = UNSET
