# @generated by datamodel-codegen:
#   filename:  confidences.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

from .confidence import agreement, likelihood, variance

type AnyConfidence = Annotated[
    agreement.ConfidenceByInterAnnotatorAgreement
    | likelihood.LikelihoodConfidence
    | variance.VarianceConfidence,
    Meta(
        description="A discriminated union of all supported columnar confidence types.",
        title="Any Confidence",
    ),
]
