# @generated by datamodel-codegen:
#   filename:  core.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import Meta

type BoppCorePrimitives = Annotated[Any, Meta(title="BOPP Core Primitives")]


type Array = Annotated[list[Any], Meta(description="A dense columnar array buffer.")]
"""
A dense columnar array buffer.
"""


type FractionItem = Annotated[
    int,
    Meta(
        description="Denominator. Strictly positive to prevent zero-division and negative bases.",
        ge=1,
    ),
]


type Fraction = Annotated[
    list[int | FractionItem],
    Meta(
        description="Rational number encoded as numerator and non-zero denominator",
        max_length=2,
        min_length=2,
    ),
]
"""
Rational number encoded as numerator and non-zero denominator
"""


type FractionNonnegativeItem = Annotated[
    int, Meta(description="Numerator, non-negative integer", ge=0)
]


type FractionNonnegativeItem1 = Annotated[
    int,
    Meta(
        description="Denominator. Strictly positive to prevent zero-division and negative bases.",
        ge=1,
    ),
]


type FractionNonnegative = Annotated[
    list[FractionNonnegativeItem | FractionNonnegativeItem1],
    Meta(description="Non-negative rational number", max_length=2, min_length=2),
]
"""
Non-negative rational number
"""
