# @generated by datamodel-codegen:
#   filename:  extents.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

from .extent import (
    midi_interval,
    midi_tick,
    pixel_box,
    score_interval,
    score_quarter,
    time_frequency_box,
    time_interval,
    times,
)

type AnyExtent = Annotated[
    times.Times
    | time_interval.TimeIntervalExtent
    | time_frequency_box.TimeFrequencyBoxExtent
    | pixel_box.PixelBoxExtent
    | score_quarter.ScoreQuarterNotes
    | score_interval.ScoreInterval
    | midi_tick.MidiTicks
    | midi_interval.MidiInterval,
    Meta(
        description="A discriminated union of all supported columnar extent types.",
        title="Any Extent",
    ),
]
