# @generated by datamodel-codegen:
#   filename:  payloads.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

from .payload import (
    beat,
    chord,
    key_mode,
    mood_thayer,
    note_hz,
    note_midi,
    object,
    onset,
    pitch_contour_hz,
    segment_multi,
    segment_open,
    tag_open,
    tempo,
)

type AnyPayload = Annotated[
    beat.BeatPositionPayload
    | chord.ChordPayload
    | key_mode.KeyModePayload
    | mood_thayer.MoodThayerPayload
    | note_hz.NoteHzPayload
    | note_midi.NoteMidiPayload
    | object.ObjectPayload
    | onset.OnsetPayload
    | pitch_contour_hz.PitchContourPayload
    | segment_multi.MultiSegmentPayload
    | segment_open.SegmentOpenPayload
    | tag_open.TagOpenPayload
    | tempo.TempoPayload,
    Meta(
        description="A discriminated union of all supported columnar payload types.",
        title="Any Payload",
    ),
]
