# @generated by datamodel-codegen:
#   filename:  metadata.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta

from . import algorithm, crowd, derived, human, other, sensor

type AnnotationMetadata = Annotated[
    human.HumanAnnotationMetadata
    | algorithm.AlgorithmAnnotationMetadata
    | crowd.CrowdSourcedAnnotationMetadata
    | sensor.SensorAnnotationMetadata
    | derived.DerivedAnnotationMetadata
    | other.AnnotationMetadataOther,
    Meta(
        description="A discriminated union of all supported metadata types.",
        title="Annotation metadata",
    ),
]
