# @generated by datamodel-codegen:
#   filename:  metadata/algorithm.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import Meta, Struct


class AlgorithmAnnotationMetadata(Struct, tag_field="metadata_type", tag="algorithm"):
    """
    Metadata for annotations created by algorithms or models.
    """

    algorithm_id: Annotated[
        str, Meta(description="A unique identifier for the algorithm.")
    ]
    version: Annotated[str, Meta(description="The version number of the algorithm.")]
    parameters: Annotated[
        dict[str, Any],
        Meta(description="A object containing the parameters used by the algorithm."),
    ]
