# @generated by datamodel-codegen:
#   filename:  metadata/crowd.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class CrowdSourcedAnnotationMetadata(Struct, tag_field="metadata_type", tag="crowd"):
    """
    Metadata for annotations created by crowdsourcing.
    """

    platform: Annotated[
        str,
        Meta(
            description="The platform or service used for crowdsourcing the annotations."
        ),
    ]
    num_annotators: Annotated[
        int,
        Meta(
            description="The number of annotators contributing to this annotation.",
            ge=1,
        ),
    ]
    consensus: Annotated[
        str,
        Meta(
            description="The method used to reach consensus among annotators (e.g., majority vote, expert review)."
        ),
    ]
