# @generated by datamodel-codegen:
#   filename:  metadata/derived.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import UNSET, Meta, Struct, UnsetType


class DerivedAnnotationMetadata(Struct, tag_field="metadata_type", tag="derived"):
    """
    Metadata describing an annotation produced by transforming or aggregating parent annotation(s).
    """

    transform: Annotated[
        str,
        Meta(
            description="The name or identifier of the operation/transform applied (e.g., 'trim', 'filter_by', 'to_times')."
        ),
    ]
    parameters: (
        Annotated[
            dict[str, Any],
            Meta(
                description="Key-value mapping of parameters passed to the transform function."
            ),
        ]
        | UnsetType
    ) = UNSET
    software: (
        Annotated[
            str,
            Meta(
                description="Software name and/or version performing the derivation (e.g., 'bopp==1.0.0')."
            ),
        ]
        | UnsetType
    ) = UNSET
    description: (
        Annotated[
            str,
            Meta(
                description="Optional human-readable description or rationale for the derivation."
            ),
        ]
        | UnsetType
    ) = UNSET
