# @generated by datamodel-codegen:
#   filename:  metadata/derived.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type SourceId = Annotated[str, Meta(pattern="^[a-zA-Z0-9]+:.*$")]


class DerivedAnnotationMetadata(Struct, tag_field="metadata_type", tag="derived"):
    """
    Metadata for annotations derived from other annotations.
    """

    source_ids: Annotated[
        list[SourceId],
        Meta(
            description="The ids of source annotations for this derived annotation.",
            min_length=1,
        ),
    ]
