# @generated by datamodel-codegen:
#   filename:  metadata/human.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class HumanAnnotationMetadata(Struct, tag_field="metadata_type", tag="human"):
    """
    Metadata for annotations created by human annotators.
    """

    annotator_id: Annotated[
        str, Meta(description="A unique identifier for the human annotator.")
    ]
    tool: Annotated[
        str, Meta(description="The tool or software used by the annotator.")
    ]
