# @generated by datamodel-codegen:
#   filename:  metadata/other.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct


class AnnotationMetadataOther(Struct, tag_field="metadata_type", tag="other"):
    """
    Metadata for annotations from unknown sources
    """

    notes: Annotated[str, Meta(description="Notes or comments about the annotation.")]
