# @generated by datamodel-codegen:
#   filename:  metadata/sensor.json

from __future__ import annotations

from typing import Annotated, Any

from msgspec import Meta, Struct


class SensorAnnotationMetadata(Struct, tag_field="metadata_type", tag="sensor"):
    """
    Metadata for annotations created by sensors or hardware.
    """

    device: Annotated[str, Meta(description="A unique identifier for the sensor.")]
    settings: Annotated[
        dict[str, Any],
        Meta(description="A object containing the settings of the device."),
    ]
