# @generated by datamodel-codegen:
#   filename:  confidence/agreement.json

from __future__ import annotations

from typing import Annotated

from msgspec import UNSET, Meta, Struct, UnsetType

type ConfidenceItem = Annotated[float, Meta(ge=0.0, le=1.0)]


type NAnnotator = Annotated[int, Meta(ge=1)]


class ConfidenceByInterAnnotatorAgreement(
    Struct, tag_field="confidence_type", tag="agreement"
):
    confidence: Annotated[
        list[ConfidenceItem],
        Meta(description="The fraction of annotators agreeing on this measurement"),
    ]
    n_annotators_common: (
        Annotated[
            int,
            Meta(
                description="The number of annotators who produced all observations",
                ge=1,
            ),
        ]
        | UnsetType
    ) = UNSET
    n_annotators: (
        Annotated[
            list[NAnnotator],
            Meta(description="The number of annotators who produced each observation"),
        ]
        | UnsetType
    ) = UNSET
