# @generated by datamodel-codegen:
#   filename:  confidence/likelihood.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class LikelihoodConfidence(Struct, tag_field="confidence_type", tag="likelihood"):
    confidence: Annotated[
        Array, Meta(description="The likeilhood (probability) of each observation")
    ]
