# @generated by datamodel-codegen:
#   filename:  confidence/variance.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct

type ConfidenceItem = Annotated[float, Meta(ge=0.0)]


class VarianceConfidence(Struct, tag_field="confidence_type", tag="variance"):
    confidence: Annotated[
        list[ConfidenceItem], Meta(description="The variance of each observation")
    ]
