# @generated by datamodel-codegen:
#   filename:  confidence/variance.json

from __future__ import annotations

from typing import Annotated

from msgspec import Meta, Struct
from pyarrow import Array


class VarianceConfidence(Struct, tag_field="confidence_type", tag="variance"):
    confidence: Annotated[Array, Meta(description="The variance of each observation")]
