name: CI Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .github/environment-test.yml
          environment-name: bopp-test
          cache-environment: true

      - name: Check code generation
        shell: bash -l {0}
        run: |
          hatch run codegen:build
          git diff --exit-code

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install --no-deps -e .

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest
